* LAB 5
* 3/26/2018
* Dean Chong San

PFDR EQU $FFFA18
DDRF EQU $FFFA1C
PFPAR EQU $FFFA1E

START:
	
		
		ORG $4000 ;THE SUB ROUTINE
		
DELAY 	MOVE #$FFFF,D0 ;START WITH A BIG NUMBER 
		
loop	dbra d0,loop ;LOOPing here
		
		RTS ;EXITS SUB ROUTINE
	
		
		ORG $3000 ;MAIN PROGRAM
		
		MOVE #$0000,PFPAR ;MAKE USE OF THE 8 PINS
		
		MOVE #$00FF,DDRF ;WRITE MODE
	
AGAIN	MOVE #$00FF,PFDR ;TO LIT UP
	
		BSR DELAY ;TO DELAY THE CHANGE OF DATA
	
		MOVE #$0000,PFDR ;TO SWITCH
	
		BSR DELAY ;TO DELAY THE CHANGE OF DATA
		
		BRA AGAIN ;RESTART TO LIT AND NOT LIT AGAIN
		
		trap #15
		DC.w $63

		
		;_________________________________________________________________
			MOVE #$0005,PEDR ;tO WRITE DATA
		MOVE #$0045,PFDR ;"E"
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		MOVE #$0001,PEDR ;INFO STROBED TO DISPLAY
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		MOVE #$0005,PEDR ;tO WRITE DATA
		MOVE #$0041,PFDR ;"A"
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		MOVE #$0001,PEDR ;INFO STROBED TO DISPLAY
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		MOVE #$0005,PEDR ;tO WRITE DATA
		MOVE #$004E,PFDR ;"N"
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		MOVE #$0001,PEDR ;INFO STROBED TO DISPLAY
		
		
		
		
		MOVE.L #BUF,A0 ;ADDRESS OF BUF IN A0
		
		MOVE #$4,D1 ;FOR THE LOOP
		
		LOOP2	BSR DELAY
	
		MOVE #$0005,PEDR ;TO ENABLE WRITING

		MOVE.B (A0)+,D2	;MOVES LETTER IN D2
		
		MOVE.B D2,PFDR ;TO GET THE LETTERS FROM THE BUFFER
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		MOVE #$0001,PEDR ;INFO STROBED TO DISPLAY
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		DBRA D1,LOOP2 ;GOES BACK TO LOOP2 TO WRITE THE NAME