* EXP 5 Part 2
* Dean Chong San
* 3/26/2018
*dbf TO INCREMENT 

PFDR EQU $FFFA18 ;HOLDS DATA
DDRF EQU $FFFA1C ;SPECIFIES DIRECTION, $00FF TO WRITE MODE
PFPAR EQU $FFFA1E 

PEDR EQU $FFFA10 ;HOLDS DATA
DDRE EQU $FFFA14 ;WRITE MODE PORT, SET TO $00FF
PEPAR EQU $FFFA16

START: 

		ORG $4000 ;THE SUB ROUTINE
		
DELAY 	MOVE #$FFFF,D0 ;START WITH A BIG NUMBER 
		
loop	dbra d0,loop ;LOOPing here
		
		RTS ;EXITS SUB ROUTINE
		

		ORG $3000 ;MAIN PROGRAM
		MOVE #$00F0,PEPAR ;TO USE LEAST 4 PINS OF E PORT
		MOVE #$00FF,DDRE ; TO ENABLE WRITE MODE
		MOVE #$0000,PFPAR ; TO USE THE 8 PINS
		MOVE #$00FF,DDRF ; TO ENABLE WRITE MODE
		
		BSR DELAY ;TO DELAY THE TRANSITION
		
		MOVE #$0004,PEDR ;PREPARE TO WRITE TO THE DISPLAY; ENABLE E2 SIGNAL
		MOVE #$000F,PFDR ;SEND DISPLAY ON CMD; FOR DATA
		MOVE #$0000,PEDR ;RESET CURSOR; NEEDS TO INCREMENT CURSOR ALSO
		
		
		
		
		BSR DELAY ;TO MAKE SURE CIRCUIT IS SETTLED
		
		MOVE #$0005,PEDR ;TO ENABLE WRITING
		MOVE #$0044,PFDR
		
		BSR DELAY
		
		MOVE #$0001,PEDR ;INFO STROBED TO DISPLAY
		
		BSR DELAY

		MOVE.L #BUF,A0 ;ADDRESS OF BUF IN A0
		
		MOVE #$4,D1 ;FOR THE LOOP
		
LOOP2	BSR DELAY
	
		MOVE #$0005,PEDR ;TO ENABLE WRITING

		MOVE.B (A0)+,D2	;MOVES LETTER IN D2
		
		MOVE D2,PFDR ;TO GET THE LETTERS FROM THE BUFFER
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		MOVE #$0001,PEDR ;INFO STROBED TO DISPLAY
		
		BSR DELAY ;DELAYS THE RATE OF SENDING DATA TO THE LCD
		
		DBRA D1,LOOP2 ;GOES BACK TO LOOP2 TO WRITE THE NAME
		
		TRAP #15
		DC.W $63
		
		
BUF DC.B 'D','E','A','N'