* LAB Exam 
* Dean Chong San
* ID : 40061194

start: 
	ORG $2000
		
		MOVE.L #$0000,A0
		MOVE.L RON,A2
		MOVE #$4,D0  ;FOR LOOP COUNTER
LOOP	CLR D1 ;SO D1 CONTAINS NOTHING
		CLR D2 ;SO D2 CONTAINS NOTHING
		MOVE.W MICK(A0),D1 ;GETTING THE VALUE OF THE MICK ARRAY INTO D1
		MOVE.W KEITH(A0),D2 ;GETTING THE VALUE OF THE KEITH ARRAY INTO D2

		
		ADD D2,D1	;GETTING THE RESULT OF THE SUM INTO D1
		MOVE.W D1,RON(A0) ;MOVING THE RESULT OF THE SUM INTO RON ARRAY
		ADD #2,A0 ;GETTING A2 TO POINT TO THE NEXT ARRAY VALUE
		DBRA D0,LOOP ;LOOP TO START ALL OVER AGAIN UNTIL
		
		TRAP #14
		DC.W $63



MICK DC 1,2,3,4,5
KEITH DC 5,4,3,2,1
RON	DS 5

	END